# Modelo base
model: models/yolov8n.pt

# Dataset
data: data/dataset.yaml

# Entrenamiento
epochs: 200
imgsz: 960
batch: 8
patience: 40
freeze: 10

# Optimizador
optimizer: AdamW
lr0: 0.001
lrf: 0.1
weight_decay: 0.0005

# Sistema
workers: 4
device: cpu   # usa "cpu" si no tienes GPU

# Salida
project: runs/train
name: pellet_yolov8
